### ISSUE TITLE
Change repository name to reflect npm package

### ISSUE THREAD

**Issue by firstdoit** [andrewrk/node-proxy-middleware#33]
Firstly, thanks for the awesome middleware.

Secondly, would you consider renaming this repository to "proxy-middleware"? It is a **very common** practice to have the npmjs and github repo named the same.

I have lost some minutes debugging why this middleware wasn't working, when the problem was I was actually installing http://npmjs.com/package/connect-proxy. I believe this must be a common mistake.

I understand this is a great name, but unless you can get the package owner to move, this difference only creates confusion.

Thanks!

**Comment by firstdoit** [comment]
@gonsfx hi! Are you the owner of npm's [connect-proxy](https://www.npmjs.com/package/connect-proxy)? If so, is your package still in use? Right now this package is named differently than the repo, which is really confusing. Do you have any ideas?

**Comment by andrewrk** [comment]
done

**Comment by firstdoit** [comment]
Nice! Thanks :)
